# Site settings
title: DECILE - Data Efficient Learning with Less Data
lab_name: DECILE
author: >
  Prateek Chanda, Ganesh Ramakrishnan and Pratik Jawanpuria
institution: IIT Bombay
email: prateekch@cse.iitb.ac.in
description: >
  DECILE tackles the challenges of data-hungry AI and deep learning by enabling
  state-of-the-art model training with only 5-10% of massive datasets, reducing
  training time/cost by an order of magnitude while significantly reducing labeled data requirements.
baseurl: ""
url: "https://efficiency-learning.github.io"
twitter_username: morinryan
github_username:  morinlab
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
